duchess-rs/duchess

examples/auth.rs
macro/src/argument.rs
macro/src/class_info.rs
macro/src/class_info/javap.rs
macro/src/class_info/javap_parser.lalrpop
macro/src/codegen.rs
macro/src/reflect.rs
src/array.rs
src/jvm.rs
src/lib.rs
src/not_null.rs
src/object.rs
src/ops.rs

get the auth example working

---

macro/src/class_info.rs
macro/src/class_info/javap.rs
macro/src/codegen.rs
macro/src/lib.rs
macro/src/reflect.rs
macro/src/span_error.rs
src/array.rs
src/collections/list.rs
src/jvm.rs
src/lib.rs
src/object.rs
src/ops.rs

These are now sufficient to autogenerate `List` and `ArrayList` (albeit removing some troublesome overloaded methods etc).

various fixes to generics

---

macro/src/codegen.rs
src/lib.rs
test-crates/viper/Cargo.toml
test-crates/viper/build.rs

* Fix https://github.com/duchess-rs/duchess/issues/24
* Clean-up the unnecessary unzip in the test crate.

Re-export jni and once_cell

---

.cargo/config.toml
examples/log.rs

The reason that I was having trouble with IDE support was that the cargo config for duchess set the classpath conditionally. No reason for that.

force classpath in duchess repository

---

book/src/SUMMARY.md
book/src/upcasts.md
examples/auth.rs
macro/src/class_info.rs
macro/src/codegen.rs
macro/src/lib.rs
macro/src/reflect.rs
macro/src/substitution.rs
macro/src/upcasts.rs
test-crates/viper/tests/test.rs

The current code stops at things outside the package, with certain very specific exceptions from the JDK (which we may need to extend).
Fixes #56

instantiate transitive upcasts

---

README.md

I felt like a chat would be useful, so I created one.
cc @duchess-rs/devs !

add link to Zulip

---

examples/auth.rs
macro/src/derive.rs

Very minor branch cleaning up the auth example.

Use derive, suppress warnings

---

Cargo.toml
README.md
book/book.toml
book/src/SUMMARY.md
book/src/call_java_from_rust.md
book/src/implementing_native_methods.md
book/src/intro.md
book/src/setup.md
book/src/tutorials.md

We've met the 0.1 release goal. Clean up our docs a bit and prepare to publish.

Release 0.1.1

---

Cargo.toml

Main change is supporting transient in the grammar.
cc @chase-ok

release 0.1.2

---

.github/workflows/rust.yml
book/src/java_function.md
examples/greeting.rs
macro/src/java_function.rs

follow-up tweaks for java functions

---

tests/ui.rs

Setting the `TESTNAME` env var while running tests will only run ui tests with that filename in their name.

Allow running just tests whose path matches a specific string.

---

Cargo.toml

change log:
* Fix `c_char` and string types for aarch64

bump release to 0.1.5

---

Cargo.toml

Includes many bug fixes, improved code generation, and more comprehensive tests.

Release 0.1.6

---

macro/src/derive.rs
src/java.rs
src/to_java.rs
test-crates/duchess-java-tests/tests/ui/derive_lifetimes.rs
test-crates/duchess-java-tests/tests/ui/duplicate_extends.stderr
test-crates/duchess-java-tests/tests/ui/duplicate_implements.stderr
test-crates/duchess-java-tests/tests/ui/examples/auth.rs
test-crates/duchess-java-tests/tests/ui/mismatched_flags_private_method_declared_as_public.stderr
test-crates/duchess-java-tests/tests/ui/mismatched_flags_public_method_declared_as_private.stderr
test-crates/duchess-java-tests/tests/ui/type_mismatch.stderr
tests/derive_lifetimes.rs

https://github.com/duchess-rs/duchess/issues/123

Add generic support

---

Cargo.toml

Release notes:
* Support lifetime parameters in `ToJava`
* Permit `duchess::Null` to pass a null value for method parameters in JAva
* Misc bug fixes

release 0.1.7

---

test-crates/Cargo.toml

add resolver 2 to remove warning

---

.github/workflows/mdbook.yml
Cargo.toml
book/src/SUMMARY.md
book/src/intro.md
book/src/safety.md
book/src/threat_model.md

Start poking on a threat model. Text is very rough and incomplete, mostly just notes, but I wanted to start the rustdoc going on.

Threat model

---

.github/workflows/autobless.yml
.github/workflows/rust.yml

implements proposal from https://github.com/duchess-rs/duchess/pull/136#issuecomment-2075658064

Automatically bless tests once a night

---

book/src/threat_model.md
src/ref_.rs

- Move section into "UB producing"
- Add doctest validating `!Send`

Update threat model

---

src/array.rs
src/error.rs
test-crates/duchess-java-tests/java/exceptions/ThrowExceptions.java
test-crates/duchess-java-tests/tests/ui/exceptions.rs
tests/test_hashmaps.rs

- Test of a thrown exception
- Test of a null pointer returned from Java
- Test of a misbehaved exception

Add tests of errors and hashmaps

---

test-crates/duchess-java-tests/tests/ui/type_mismatch_bad_argument_type.rs
test-crates/duchess-java-tests/tests/ui/type_mismatch_bad_argument_type_explicit.rs

the bless job doesn't seem to actually work for permissions reasons (but I'm also not convinced by the code it's trying to commit anyway). 
Manually update tests to fix CI.

update tests for new rustc version

---

.github/workflows/autobless.yml
test-crates/duchess-java-tests/tests/ui/create_string_from_bytes.stderr
test-crates/duchess-java-tests/tests/ui/duplicate_extends.stderr
test-crates/duchess-java-tests/tests/ui/duplicate_implements.stderr
test-crates/duchess-java-tests/tests/ui/examples/generics.stderr
test-crates/duchess-java-tests/tests/ui/exceptions.stderr
test-crates/duchess-java-tests/tests/ui/mismatched_flags_private_method_declared_as_public.stderr
test-crates/duchess-java-tests/tests/ui/mismatched_flags_public_method_declared_as_private.stderr
test-crates/duchess-java-tests/tests/ui/must_use_jvmop.stderr
test-crates/duchess-java-tests/tests/ui/native_fn_return_fresh_java_string.stderr
test-crates/duchess-java-tests/tests/ui/native_fn_return_local_java_string.stderr
test-crates/duchess-java-tests/tests/ui/type_mismatch_bad_argument_type.stderr
test-crates/duchess-java-tests/tests/ui/type_mismatch_bad_argument_type_explicit.stderr
test-crates/duchess-java-tests/tests/ui/type_mismatch_bad_argument_type_in_decl.stderr
test-crates/duchess-java-tests/tests/ui/type_mismatch_return_type_in_Object_hashCode.stderr

The autobless still won't work, as it doesn't have permissions, but at least it should do minimal work now

Some bless/autobless changes

---

.gitignore
test-crates/duchess-java-tests/tests/ui/examples/auth.rs
test-crates/duchess-java-tests/tests/ui/examples/greeting.rs
test-crates/duchess-java-tests/tests/ui/examples/log.rs
test-crates/duchess-java-tests/tests/ui/examples/log_global_ref_and_chained_calls.rs
test-crates/duchess-java-tests/tests/ui/examples/log_global_ref_and_two_calls.rs
test-crates/duchess-java-tests/tests/ui/examples/log_local_ref_and_two_calls.rs
test-crates/duchess-java-tests/tests/ui/examples/log_one_big_call.rs
test-crates/duchess-java-tests/tests/ui/instance_method_from_superclass.rs
test-crates/duchess-java-tests/tests/ui/instance_method_fully_qualified.rs
test-crates/duchess-java-tests/tests/ui/static_method_invocation.rs
test-crates/duchess-java-tests/tests/ui/to_java_java_refs.rs
test-crates/duchess-java-tests/tests/ui/to_java_produce_local_java_ref.rs

Update all `ui` tests from`@check-pass` to `@run`.
Ignores `ui/passing_null_values.rs` update bc it fails for `Error: attempted to deref a null Java object pointer`

Run existing UI tests

---

CHANGELOG.md
Cargo.toml

Increment version and update Changelog.

Bump version and update changelog

---

book/src/threat_model.md

Just a few tiny nitpicks I found reading that threat model.

Couple of smaller doc fixes

---

CONTRIBUTING.md

Update contributor guidelines on how to run a single test

Update contributor guidelines on how to run a single test

---

test-crates/duchess-java-tests/src/java_wrapper.rs

https://github.com/duchess-rs/duchess/issues/146

Add -Xcheck:jni to java-to-rust tests
