macro/src/codegen.rs

Use the same `OnceCell` caching mechanism for looking up method IDs for constructor and method calls. This forces us to switch to the `*_unchecked()` JNI functions. The checks in the regular versions should be redundant with our own type system. It also avoids parsing the method signature string on each call!

Cache MethodID for constructor & method calls

---

examples/logger.rs
macro/Cargo.toml
macro/src/codegen.rs
src/cast.rs
src/catch.rs
src/inspect.rs
src/jvm.rs
src/lib.rs

The `by_type!` macro allows users to write a pseudo-match expression
that tries to downcast a Java object into a given class or interface.
It's intended mainly for inspecting the output Java APIs that can throw different
kinds of exceptions for different error cases. 
---
Also add support for multiple catch arms and a `finally` block.

Add by_type! macro, multiple catch arms, finally block

---

macro/build.rs

This is a workaround for https://github.com/duchess-rs/duchess/issues/7. It forces a recompilation of the procedural macro whenever the `CLASSPATH` environment variable on which it depends changes.

Recompile when CLASSPATH changes

---

macro/build.rs
macro/src/class_info.rs
macro/src/class_info/javap_parser.lalrpop
macro/src/codegen.rs
test-crates/viper/src/main.rs

This PR improves the parsing of classes generated from Scala code:
* Support constructors listed after methods 
* Support generics with an upper bound, e.g. `<T extends viper.silver.ast.Node>`
* Add a missing `$` to the grammar of method descriptors
Fixes #36

Fix parsing of bytecode generated from Scala

---

src/error.rs
src/jvm.rs
test-crates/viper/tests/test.rs
tests/bad_jvm_construction_1.rs
tests/bad_jvm_construction_2.rs
tests/good_jvm_construction_1.rs
tests/good_jvm_construction_2.rs

Implementation of what described in https://github.com/duchess-rs/duchess/issues/6. The global JVM is stored in a `once_cell::sync::OnceCell` to ensure that it's only constructed once via duchess' API. Other types that I considered and discarded:
* `once_cell::sync::Lazy` has no way of postponing the declaration of the constructor,
* `once_cell::race::onceBox` doesn't prevent concurrent invocations of the constructor, 
* `std::sync::OnceLock` depends on unstable features.
Fixes #6.

Implement `JvmBuilder`

---

macro/src/class_info.rs
macro/src/class_info/javap_parser.lalrpop
test-crates/viper/src/lib.rs

Fix the grammar to support `interface Foo extends A, B, C`.

Parse interfaces with multiple extends

---

Cargo.toml
book/src/internals.md
book/src/jvm.md
book/src/reference.md
examples/auth.rs
macro/src/codegen.rs
src/array.rs
src/cast.rs
src/error.rs
src/find.rs
src/java.rs
src/jvm.rs
src/lib.rs
src/libjvm.rs
src/not_null.rs
src/raw.rs
src/ref_.rs
src/str.rs
src/thread.rs
test-crates/viper/build.rs
test-crates/viper/tests/test.rs
tests/bad_jvm_construction_1.rs
tests/bad_jvm_construction_2.rs
tests/good_jvm_construction_2.rs

The `jni` crate provides a thin wrapper on top of the `jni-sys` headers and we were often writing more complicated code to use it instead of making direct `jni-sys` calls. It also gives us more flexibility around exception handling, `libjvm` linking, and users brining their own JVM instance.
The `raw` mod now contains most of the newtype wrappers we need around `jni-sys` pointers.
This commit adds an optional `dylibjvm` feature that gives the same dynamic linking behavior as the `jni` crate. Without it, it expects `libjvm` to be statically linked. It also adds a friendly thrown-error message.
Some of the initialization and string-passing code should be marginally faster since we avoid some copies into and out of cesu8 and c encodings.

Use `jni-sys` directly instead of through `jni`

---

src/jvm.rs
src/raw.rs
tests/racing_jvm_construction.rs

Fixes a race condition when multiple threads try to create or look up existing JVMs at the same time by sequencing the calls behind the `GLOBAL_JVM` sync cell.
Marked the raw fns as `unsafe` and added a test case for regression. Test is a bit racy without the fix (may panic or segfault depending on sequencing), but confirmed we get
```
process didn't exit successfully: `... race_multiple_threads_to_launch_jvm --exact --nocapture` (signal: 11, SIGSEGV: invalid memory reference)
```
without the fix and ok with it.

Fix race condition in JVM creation

---

macro/src/class_info/javap_parser.lalrpop
macro/src/codegen.rs
src/find.rs
src/lib.rs
src/ops.rs
src/raw.rs
test-crates/viper/src/lib.rs
test-crates/viper/tests/test.rs

General improvements:
* I extended the grammar in order to accept the `throws java/lang/IndexOutOfBoundsException` that `javap` generates, where the class reference uses `/` instead of `.`.
* `javap` outputs `public static {};` for classes with a static initialization block, also called `<clinit>`. I extended the grammar to parse and ignore that, since the initialization block is automatically executed by the JVM when necessary.
* I hit the issue https://github.com/duchess-rs/duchess/issues/41: in `java_package!` I needed to write `ArrayBuffer` but then the compiler was complaining that a type parameter was missing. So, I added a `java::lang::Object` default to *every* generated type parameter.
To support identifiers with `$` (https://github.com/duchess-rs/duchess/issues/12):
* Parsing …

Improvements to use Scala's companion objects

---

Cargo.toml
README.md
macro/Cargo.toml
macro/src/signature.rs
tests/ui.rs
tests/ui/type_mismatch.rs
tests/ui/type_mismatch.stderr

fixes #5
I was unable to improve the error span further, as the duchess parser stringifies the class body before parsing with larlpop. We'd need to teach larlpop to handle token streams first.
Alternatively we can use the offset in the stringified version to walk the token stream to find the same offset and use that span.

Add ui test suite

---

macro/src/check.rs
macro/src/class_info.rs
tests/ui/duplicate_extends.rs
tests/ui/duplicate_extends.stderr
tests/ui/duplicate_implements.rs
tests/ui/duplicate_implements.stderr

Provide a simple error message if there are deplicate references for "extends" or "implements" in the class declaration.
Closes #43

Detect duplicate references in "extends" and "implements"

---

examples/auth.rs
macro/src/class_info.rs
macro/src/derive.rs
src/java.rs
tests/ui/derive_scalar_fields.rs

Adds support for scalar fields, which aren't a part of the `Upcast`
object heirarchy, by just copying them from the struct as is.
Along the way
1. Make sure we rustify the method name
2. Prefix duchess types with `duchess` in generated code
3. Add `java.lang.Instant` bindings, which are convenient and give an
example of using a scalar field (epoch millis) when deriving.

Add scalar field support for derive ToJava, small derive bug fixes

---

book/src/setup.md
macro/src/reflect.rs
src/str.rs

Some systems have multiple Java versions present and it's easy for the `javap` from one JDK to end up earlier on the path than the `javap` we're building against. The `JAVA_HOME` env var is a canonical way to identify and pass the JDK/JRE location to programs. We already use it for locating `libjvm` at runtime! If no `JAVA_HOME` was set, we fall back to relying on `PATH`, like we do for `libjvm`.
Updated the setup docs as well.

Use `$JAVA_HOME/bin/javap` if `$JAVA_HOME` is set

---

src/jvm.rs
src/str.rs

ARM implementation of `c_char` is `u8` which causes a build failure for type mismatch when running `cargo build`
Update Duchess' JNINativeMethod type conversion to the general `c_char`
```
error[E0308]: mismatched types
--> src/jvm.rs:286:27
|
286 |                     name: java_function.name.as_ptr() as *mut i8,
|                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `*mut u8`, found `*mut i8`
|
= note: expected raw pointer `*mut u8`
found raw pointer `*mut i8`
```
- `cargo build`

Fix type mismatch for ARM's c_char

---

macro/src/codegen.rs
macro/src/derive.rs
macro/src/java_function.rs
macro/src/signature.rs
test-crates/viper/src/lib.rs

Fixes #108.
All `std::*` paths changed to `::core::*`. All `duchess` types imported in codegen are now referred to through `duchess::*` paths. Trait method calls are spelled out to avoid importing the trait.

Refer to `duchess` and `core` types explicitly

---

.github/workflows/rust.yml
test-crates/duchess-java-tests/Cargo.toml
test-crates/duchess-java-tests/tests/ui.rs

This PR tests duchess on Windows and macOS as part of the CI.
For simplicity, `mdBook test` is still only executed on Ubuntu. To have something cross-platform for mdbook it might be better to use some published GitHub action.
Note that I upgraded the `ui_test` dependency from version `0.10` to `0.15`. Since `ui_test` `0.15` uses recently stabilized Rust features, users might have to do a `rustup update` before compiling duchess.

Run tests on macOS and Windows

---

book/src/internals.md
macro/src/codegen.rs
macro/src/parse.rs
macro/src/signature.rs
src/array.rs
src/cast.rs
src/error.rs
src/find.rs
src/jvm.rs
src/lib.rs
src/raw.rs
src/ref_.rs
src/str.rs
src/to_java.rs
tests/string.rs

This commit fixes a few safety bugs in the string and local ref code. It also cleans up the `invoke` code to make it easier to always free local refs. The `HasEnvPtr` trait was no longer providing any value so removed it along the way.
Bugs:
1. Returning an empty string from Java would result in writing to a null pointer, since `Vec::with_capacity(0)` does not allocate and the JNI string functions always write a trailing nul byte.
2. Allocate one extra byte in general when decoding Java strings to account for the trailing nul.
3. Always wrap the return result of JNI function calls that can return a Java object in a `Local` before doing anything else, like checking for an exception. This ensures `Local::drop` is called and the ref is correctly freed.
4. Fix up a few places where exceptions …

Fix str and local free bugs

---

book/src/call_java_from_rust.md

Thank you for building duchess, I've had a lot of fun testing it out today to replace a house of cards I have in a toy project! I found that having the `pub` present in the macro input would lead to a compile error along the  lines of "unexpected input".
I suspect that at some point this support for visibility was removed? Or maybe it's a placeholder for functionality yet planned for implementation?

remove `pub` from package in `java_package!` example

---

CONTRIBUTING.md
README.md
justfile
macro/Cargo.toml
macro/src/lib.rs
macro/src/reflect.rs
src/null.rs
test-crates/rust-toolchain.toml

- Pin a rust toolchain for test-crates since the expectations depend on a specific Rust version
- Add a contribution guide
- Improve (and document) `DUCHESS_DEBUG`. DUCHESS_DEBUG will now dump the formatted Rust code to the file and print clickable links to the terminal.

Improvements to `DUCHESS_DEBUG` and other misc small changes

---

.github/workflows/rust.yml
justfile
test-crates/duchess-java-tests/tests/ui.rs
tests/arrays.rs

1. Adds testing against JDK 21
2. Adds a `just coverage` target. This produces a coverage report that covers both the duchess library & the proc macro as well. It changes the ui-test framework to conditionally run rustc with `-C instrument-coverage`.
3. Adds some unit tests to validate that the coverage report is working.
In CI, a the coverage report is added as an archive.
Cargo llvm-cov seeks to accomplish a lot of the same things, but it can't properly (and I don't think it can be configured to) properly construct the right llvm-cov incantation to produce a unified coverage report. I wasn't able to get it to not just crash.

Coverage testing

---

book/src/threat_model.md
macro/src/codegen.rs
macro/src/java_function.rs
src/into_rust.rs
src/jvm.rs
test-crates/duchess-java-tests/java/type_mismatch/TakesInt.java
test-crates/duchess-java-tests/tests/ui.rs
test-crates/duchess-java-tests/tests/ui/create_string_from_bytes.rs
test-crates/duchess-java-tests/tests/ui/native_fn_return_fresh_java_string.rs
test-crates/duchess-java-tests/tests/ui/native_fn_return_fresh_java_string.stderr
test-crates/duchess-java-tests/tests/ui/native_fn_return_local_java_string.rs
test-crates/duchess-java-tests/tests/ui/native_fn_return_local_java_string.stderr
test-crates/duchess-java-tests/tests/ui/type_mismatch_bad_argument_type.rs
test-crates/duchess-java-tests/tests/ui/type_mismatch_bad_argument_type.stderr
test-crates/duchess-java-tests/tests/ui/type_mismatch_bad_argument_type_explicit.rs
test-crates/duchess-java-tests/tests/ui/type_mismatch_bad_argument_type_explicit.stderr
test-crates/duchess-java-tests/tests/ui/type_mismatch_bad_argument_type_in_decl.rs
test-crates/duchess-java-tests/tests/ui/type_mismatch_bad_argument_type_in_decl.stderr
test-crates/duchess-java-tests/tests/ui/type_mismatch_return_type_in_Object_hashCode.rs
test-crates/duchess-java-tests/tests/ui/type_mismatch_return_type_in_Object_hashCode.stderr

Finished write-up, added some tests

More work on threat model

---

.github/workflows/mdbook.yml
README.md
book/src/intro.md
book/src/threat_model.md
test-crates/rust-toolchain.toml

This CR publishes coverage information to GitHub pages when PRs are merged to main. Coverage is in a subdirectory of the main site, so all existing links continue to work. You can play around with how this will work on my [fork](https://rcoh.github.io/duchess/)
I also updated the README to add some links to the coverage information.
Along the way, I fixed some broken links and typos in the threat model and deleted rust-toolchain since we now have the bless script.

Automatically publish coverage information to GitHub pages

---

justfile
src/find.rs
test-crates/duchess-java-tests/java/exceptions/DifferentException.java
test-crates/duchess-java-tests/java/exceptions/ThrowExceptions.java
test-crates/duchess-java-tests/tests/ui/exceptions.rs
tests/nested_jvm.rs

Adds coverage for a few more areas that were missing coverage (previous: 63%, now 67%)
- reading static fields
- catching exceptions with `.catch()`
- correctly forbidding nested JVMs from being created
In the process I discovered #142 which I'm not sure how to best fix. There is a test included here that reproduces that behavior.

Add additional test coverage

---

src/jvm.rs
test-crates/duchess-java-tests/tests/ui/examples/log.rs
test-crates/duchess-java-tests/tests/ui/must_use_jvmop.rs

It's very easy to accidentally avoid calling execute because of how Rust-like Duchess makes calling Java code. As an example, one of our own examples failed to call execute!

Add `must_use` to JvmOp

---

macro/src/class_info.rs
macro/src/codegen.rs
macro/src/java_function.rs
test-crates/duchess-java-tests/build.rs
test-crates/duchess-java-tests/java/generics/EventKey.java
test-crates/duchess-java-tests/java/generics/MapKey.java
test-crates/duchess-java-tests/java/generics/MapLike.java
test-crates/duchess-java-tests/tests/ui/examples/generics.rs

Fixes: https://github.com/duchess-rs/duchess/issues/42
Fixes: https://github.com/duchess-rs/duchess/issues/149
Generics were not code generated properly. They should actually refer to the first class in the list of extending classes. This introduces `GenericsScope` to keep track of where generics were defined when creating descriptors.

Fix method descriptor for `X extends Y`

---

src/java.rs
test-crates/duchess-java-tests/tests/ui/examples/memory_usage.rs

Currently, there is not straightforward way of defining a `java.*` package outside of Duchess

Add JMX APIs to Java prelude

---

CONTRIBUTING.md

The guide states that rust 1.76 is needed to run the UI tests and it
links to a non-existent file.
The UI tests do not run with rust 1.76. This change removes the link to
the non-existent file and updates the text to reflect rust 1.79 is
needed.

Update contributor guide.

---

book/src/safety.md
book/src/threat_model.md

After some investigation, there does not seem to be any loss of safety possible when incorrect `.class` files are used.

Update thread model to include new understandings

---

Cargo.toml
macro/src/check.rs
macro/src/reflect.rs
test-crates/duchess-java-tests/tests/ui/examples/log.rs
test-crates/duchess-java-tests/tests/ui/examples/log_global_ref_and_chained_calls.rs
test-crates/duchess-java-tests/tests/ui/examples/log_global_ref_and_two_calls.rs
test-crates/duchess-java-tests/tests/ui/examples/log_local_ref_and_two_calls.rs
test-crates/duchess-java-tests/tests/ui/examples/log_one_big_call.rs
test-crates/duchess-java-tests/tests/ui/interface_class_mismatch_reflected.rs
test-crates/duchess-java-tests/tests/ui/interface_class_mismatch_reflected.stderr
test-crates/duchess-java-tests/tests/ui/interface_class_mismatch_specified.rs
test-crates/duchess-java-tests/tests/ui/interface_class_mismatch_specified.stderr
test-crates/viper/src/lib.rs

Works for both fully reflected classes and for specified classes. Added UI tests for both cases, and updated other portions where needed to specify the correct type of Java import.
For Reflected classes, fixed an error in specifying the span and kind of the class. Previously, they took the span of the reflection cache, which meant that the error could confusingly point to the main `java_package!` macro invocation.
Fixes #67.

Add in checks for the type of Java Class/Interface

---

macro/src/check.rs
test-crates/duchess-java-tests/tests/ui/duplicate_extends.rs
test-crates/duchess-java-tests/tests/ui/duplicate_extends.stderr
test-crates/duchess-java-tests/tests/ui/duplicate_implements.rs

Ensures that all errors are propagated to users of the library, to be able to be fixed in one go.
Very few UI tests are broken by this, updated the two that needed updates.

Add support for multiple Errors to surface

---

book/src/threat_model.md
src/java.rs
src/jvm.rs
test-crates/duchess-java-tests/tests/java-to-rust/java/java_rust_initiated_exceptions/JavaRustExceptions.java
test-crates/duchess-java-tests/tests/java-to-rust/java/java_rust_java_exception/JavaRustJavaException.java
test-crates/duchess-java-tests/tests/java-to-rust/java/java_rust_java_exception/JavaRustJavaNPE.java
test-crates/duchess-java-tests/tests/java-to-rust/rust-libraries/java_rust_initiated_exceptions.rs
test-crates/duchess-java-tests/tests/java-to-rust/rust-libraries/java_rust_java_exception.rs
test-crates/duchess-java-tests/tests/java-to-rust/rust-libraries/java_rust_java_npe.rs
test-crates/duchess-java-tests/tests/ui.rs

This change updates native_function_returning_object and native_function_returning_scalar to translate crate::Error and rust panics into a corresponding Java exception.
https://github.com/duchess-rs/duchess/issues/173

Java to rust exceptions

---

book/src/SUMMARY.md
book/src/java_signatures_in_rust.md
macro/src/class_info.rs
macro/src/class_info/javap.rs
macro/src/codegen.rs
macro/src/signature.rs
src/array.rs
src/cast.rs
src/into_rust.rs
src/jvm.rs
src/lib.rs
src/not_null.rs
src/ops.rs
src/ref_.rs
src/try_catch.rs
test-crates/duchess-java-tests/tests/rust-to-java/type_mismatch_bad_argument_type.rs
test-crates/duchess-java-tests/tests/rust-to-java/type_mismatch_bad_argument_type_explicit.rs

I had a branch implementing the ability for Rust types to implement Java callbacks. I'm taking a fresh approach but these commits are some small refactorings that I want to land first and which will be used by the new code.
r? @rcoh

cherry-pick some refactorings

---

duchess-reflect/src/codegen.rs
test-crates/duchess-java-tests/java/derives/OptionalFields.java
test-crates/duchess-java-tests/tests/rust-to-java/derive_options.rs
test-crates/duchess-java-tests/tests/rust-to-java/passing_null_values.rs
tests/string.rs

Prior to this codegen change, the test fails with the somewhat cryptic:
```
full stderr:
Error: attempted to deref a null Java object pointer
full stdout:
```
This occurs because when we convert `None` into a JRef, it becomes `Result<T, NullJRef>`. When the generated code calls `?` on that result, it bails out.
But, in this case we actually **want** to pass null. I updated it to use `.ok();` instead—this produces an `Option<T>` instead of a result, causing the later code to convert `None` into the JNI ref as intended.
Before:
```rust
let a0 = self.a0.into_as_jref(jvm)?;
let a0 = duchess::prelude::AsJRef::as_jref(&a0)?;
let a1 = self.a1.into_as_jref(jvm)?;
let a1 = duchess::prelude::AsJRef::as_jref(&a1)?;
```
After:
```rust
let a0 = self.a0.into_as_jref(jvm)?;
let a0 = …
```

Fix `Option<T>` fields when used as method arguments as well as in `ToJava`

---

.github/workflows/autobless.yml

Duchess autobless [fails](https://github.com/duchess-rs/duchess/actions/runs/10313816006) to auto create create PR's when there are no changes.
We update autobless to check for change before creating a PR.
```
Run gh pr create -B main --title 'Automatic bless' --body ''
pull request create failed: GraphQL: No commits between main and bless-2024-08-0[9](https://github.com/duchess-rs/duchess/actions/runs/10313816006/job/28551205865#step:9:10) (createPullRequest)
```

Fix autobless

---

test-crates/duchess-java-tests/tests/java-to-rust/java/java_to_rust_arrays/JavaArrayTests.java
test-crates/duchess-java-tests/tests/java-to-rust/rust-libraries/native_fn_arrays.rs

I found it difficult to make use of arrays with JNI functions. I'm adding these ui tests to give an example to others.

Add array tests to the java-to-rust ui tests

---

CONTRIBUTING.md
Cargo.toml
build.rs
duchess-build-rs/Cargo.toml
duchess-build-rs/src/derive_java.rs
duchess-build-rs/src/files.rs
duchess-build-rs/src/impl_java_trait.rs
duchess-build-rs/src/java_package_macro.rs
duchess-build-rs/src/lib.rs
duchess-build-rs/src/log.rs
duchess-build-rs/src/re.rs
duchess-build-rs/test-files/java_package_1.rs
duchess-reflect/Cargo.toml
duchess-reflect/src/argument.rs
duchess-reflect/src/check.rs
duchess-reflect/src/class_info.rs
duchess-reflect/src/codegen.rs
duchess-reflect/src/config.rs
duchess-reflect/src/reflect.rs
duchess-reflect/src/reflect/javap.rs
justfile
macro/src/derive.rs
macro/src/java_function.rs
src/java.rs
src/link.rs
src/thread.rs
test-crates/viper/Cargo.toml
test-crates/viper/build.rs
tests/arrays.rs

Moves javap into build.rs. Error handling works pretty well. There is one missing piece to also capture `#[java...]` derives
since those must also be reflected in build.rs.

pretty-close-to-build-rs
